#!/usr/bin/env bash

. "$(dirname "$0")"/msvcenv.sh

# Approximate command-line length (including spaces between arguments).
if ((${#*} > 30000)); then
    rsp=$(mktemp "${TMPDIR:-/tmp}/lib.XXXXXX.rsp") || exit 1
    trap 'rm -f "$rsp"' EXIT

    for arg in "$@"; do
        printf '%s\n' "$arg" >>"$rsp"
    done

    exec "$(dirname "$0")"/wine-msvc.sh "$BINDIR"/lib.exe "@$rsp"
else
    exec "$(dirname "$0")"/wine-msvc.sh "$BINDIR"/lib.exe "$@"
fi
